# Generated by Django 5.0.1 on 2024-01-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sami', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='human',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='human',
            name='image',
            field=models.ImageField(default='def.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='human',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
